[package]
name = "gb-emu"
version = "0.1.0"
authors = ["earacena <30157858+earacena@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
